### ISSUE TITLE
How to let the computer control IT6322a through USB?

### ISSUE THREAD

**Issue by t2015q** [hmdyt/miraclue_low_voltage_monitor#2]
Hello, 
     Recently, I was researching how to control the power supply by code. Thank Goodness! I happened to come across this script, Could you tell me how to use this script to control it? I control IT6322A on windows,Thanks!

Muki

**Comment by hmdyt** [comment]
Hi, thanks for taking a look at my repository.

This repository is designed to be used with the repository here (https://github.com/hmdyt/IT6322A_server).

**Comment by t2015q** [comment]
Thank you ! It worked well.

**Comment by t2015q** [comment]
Close
